version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'strip-indent'
        update-types:
          - 'version-update:semver-major'
